/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ErreurConnexionRouteImport } from './routes/erreur-connexion'
import { Route as FoyerRouteImport } from './routes/foyer'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as JumelerRouteImport } from './routes/jumeler'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as FoyerIndexRouteImport } from './routes/foyer.index'
import { Route as FoyerStudentIdRouteImport } from './routes/foyer.$studentId'
import { Route as SeanceSessionIdRouteImport } from './routes/seance.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ErreurConnexionRoute = ErreurConnexionRouteImport.update({
  id: '/erreur-connexion',
  path: '/erreur-connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const FoyerRoute = FoyerRouteImport.update({
  id: '/foyer',
  path: '/foyer',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const JumelerRoute = JumelerRouteImport.update({
  id: '/jumeler',
  path: '/jumeler',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const FoyerIndexRoute = FoyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoyerRoute,
} as any)
const FoyerStudentIdRoute = FoyerStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => FoyerRoute,
} as any)
const SeanceSessionIdRoute = SeanceSessionIdRouteImport.update({
  id: '/seance/$sessionId',
  path: '/seance/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/foyer': typeof FoyerRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/jumeler': typeof JumelerRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer/': typeof FoyerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/jumeler': typeof JumelerRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer': typeof FoyerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/foyer': typeof FoyerRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/jumeler': typeof JumelerRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer/': typeof FoyerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/erreur-connexion'
    | '/foyer'
    | '/inscription'
    | '/jumeler'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/erreur-connexion'
    | '/inscription'
    | '/jumeler'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/erreur-connexion'
    | '/foyer'
    | '/inscription'
    | '/jumeler'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  ErreurConnexionRoute: typeof ErreurConnexionRoute
  FoyerRoute: typeof FoyerRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  JumelerRoute: typeof JumelerRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  SeanceSessionIdRoute: typeof SeanceSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erreur-connexion': {
      id: '/erreur-connexion'
      path: '/erreur-connexion'
      fullPath: '/erreur-connexion'
      preLoaderRoute: typeof ErreurConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foyer': {
      id: '/foyer'
      path: '/foyer'
      fullPath: '/foyer'
      preLoaderRoute: typeof FoyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumeler': {
      id: '/jumeler'
      path: '/jumeler'
      fullPath: '/jumeler'
      preLoaderRoute: typeof JumelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foyer/': {
      id: '/foyer/'
      path: '/'
      fullPath: '/foyer/'
      preLoaderRoute: typeof FoyerIndexRouteImport
      parentRoute: typeof FoyerRoute
    }
    '/foyer/$studentId': {
      id: '/foyer/$studentId'
      path: '/$studentId'
      fullPath: '/foyer/$studentId'
      preLoaderRoute: typeof FoyerStudentIdRouteImport
      parentRoute: typeof FoyerRoute
    }
    '/seance/$sessionId': {
      id: '/seance/$sessionId'
      path: '/seance/$sessionId'
      fullPath: '/seance/$sessionId'
      preLoaderRoute: typeof SeanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoyerRouteChildren {
  FoyerStudentIdRoute: typeof FoyerStudentIdRoute
  FoyerIndexRoute: typeof FoyerIndexRoute
}

const FoyerRouteChildren: FoyerRouteChildren = {
  FoyerStudentIdRoute: FoyerStudentIdRoute,
  FoyerIndexRoute: FoyerIndexRoute,
}

const FoyerRouteWithChildren = FoyerRoute._addFileChildren(FoyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  ErreurConnexionRoute: ErreurConnexionRoute,
  FoyerRoute: FoyerRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  JumelerRoute: JumelerRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  SeanceSessionIdRoute: SeanceSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
