/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentRouteImport } from './routes/_parent'
import { Route as ErreurConnexionRouteImport } from './routes/erreur-connexion'
import { Route as FoyerRouteImport } from './routes/foyer'
import { Route as JumelerRouteImport } from './routes/jumeler'
import { Route as MemoireRouteImport } from './routes/memoire'
import { Route as ParentConnexionRouteImport } from './routes/_parent.connexion'
import { Route as ParentInscriptionRouteImport } from './routes/_parent.inscription'
import { Route as ParentMotDePasseOublieRouteImport } from './routes/_parent.mot-de-passe-oublie'
import { Route as ParentNouveauMotDePasseRouteImport } from './routes/_parent.nouveau-mot-de-passe'
import { Route as FoyerIndexRouteImport } from './routes/foyer.index'
import { Route as FoyerStudentIdRouteImport } from './routes/foyer.$studentId'
import { Route as SeanceSessionIdRouteImport } from './routes/seance.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/_parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ErreurConnexionRoute = ErreurConnexionRouteImport.update({
  id: '/erreur-connexion',
  path: '/erreur-connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const FoyerRoute = FoyerRouteImport.update({
  id: '/foyer',
  path: '/foyer',
  getParentRoute: () => rootRouteImport,
} as any)
const JumelerRoute = JumelerRouteImport.update({
  id: '/jumeler',
  path: '/jumeler',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoireRoute = MemoireRouteImport.update({
  id: '/memoire',
  path: '/memoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentConnexionRoute = ParentConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => ParentRoute,
} as any)
const ParentInscriptionRoute = ParentInscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMotDePasseOublieRoute = ParentMotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNouveauMotDePasseRoute = ParentNouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => ParentRoute,
} as any)
const FoyerIndexRoute = FoyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoyerRoute,
} as any)
const FoyerStudentIdRoute = FoyerStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => FoyerRoute,
} as any)
const SeanceSessionIdRoute = SeanceSessionIdRouteImport.update({
  id: '/seance/$sessionId',
  path: '/seance/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/foyer': typeof FoyerRouteWithChildren
  '/jumeler': typeof JumelerRoute
  '/memoire': typeof MemoireRoute
  '/connexion': typeof ParentConnexionRoute
  '/inscription': typeof ParentInscriptionRoute
  '/mot-de-passe-oublie': typeof ParentMotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof ParentNouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer/': typeof FoyerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/jumeler': typeof JumelerRoute
  '/memoire': typeof MemoireRoute
  '/connexion': typeof ParentConnexionRoute
  '/inscription': typeof ParentInscriptionRoute
  '/mot-de-passe-oublie': typeof ParentMotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof ParentNouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer': typeof FoyerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_parent': typeof ParentRouteWithChildren
  '/erreur-connexion': typeof ErreurConnexionRoute
  '/foyer': typeof FoyerRouteWithChildren
  '/jumeler': typeof JumelerRoute
  '/memoire': typeof MemoireRoute
  '/_parent/connexion': typeof ParentConnexionRoute
  '/_parent/inscription': typeof ParentInscriptionRoute
  '/_parent/mot-de-passe-oublie': typeof ParentMotDePasseOublieRoute
  '/_parent/nouveau-mot-de-passe': typeof ParentNouveauMotDePasseRoute
  '/foyer/$studentId': typeof FoyerStudentIdRoute
  '/seance/$sessionId': typeof SeanceSessionIdRoute
  '/foyer/': typeof FoyerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/erreur-connexion'
    | '/foyer'
    | '/jumeler'
    | '/memoire'
    | '/connexion'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/erreur-connexion'
    | '/jumeler'
    | '/memoire'
    | '/connexion'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer'
  id:
    | '__root__'
    | '/'
    | '/_parent'
    | '/erreur-connexion'
    | '/foyer'
    | '/jumeler'
    | '/memoire'
    | '/_parent/connexion'
    | '/_parent/inscription'
    | '/_parent/mot-de-passe-oublie'
    | '/_parent/nouveau-mot-de-passe'
    | '/foyer/$studentId'
    | '/seance/$sessionId'
    | '/foyer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentRoute: typeof ParentRouteWithChildren
  ErreurConnexionRoute: typeof ErreurConnexionRoute
  FoyerRoute: typeof FoyerRouteWithChildren
  JumelerRoute: typeof JumelerRoute
  MemoireRoute: typeof MemoireRoute
  SeanceSessionIdRoute: typeof SeanceSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent': {
      id: '/_parent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erreur-connexion': {
      id: '/erreur-connexion'
      path: '/erreur-connexion'
      fullPath: '/erreur-connexion'
      preLoaderRoute: typeof ErreurConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foyer': {
      id: '/foyer'
      path: '/foyer'
      fullPath: '/foyer'
      preLoaderRoute: typeof FoyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumeler': {
      id: '/jumeler'
      path: '/jumeler'
      fullPath: '/jumeler'
      preLoaderRoute: typeof JumelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoire': {
      id: '/memoire'
      path: '/memoire'
      fullPath: '/memoire'
      preLoaderRoute: typeof MemoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent/connexion': {
      id: '/_parent/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ParentConnexionRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/inscription': {
      id: '/_parent/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof ParentInscriptionRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/mot-de-passe-oublie': {
      id: '/_parent/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof ParentMotDePasseOublieRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/nouveau-mot-de-passe': {
      id: '/_parent/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof ParentNouveauMotDePasseRouteImport
      parentRoute: typeof ParentRoute
    }
    '/foyer/': {
      id: '/foyer/'
      path: '/'
      fullPath: '/foyer/'
      preLoaderRoute: typeof FoyerIndexRouteImport
      parentRoute: typeof FoyerRoute
    }
    '/foyer/$studentId': {
      id: '/foyer/$studentId'
      path: '/$studentId'
      fullPath: '/foyer/$studentId'
      preLoaderRoute: typeof FoyerStudentIdRouteImport
      parentRoute: typeof FoyerRoute
    }
    '/seance/$sessionId': {
      id: '/seance/$sessionId'
      path: '/seance/$sessionId'
      fullPath: '/seance/$sessionId'
      preLoaderRoute: typeof SeanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ParentRouteChildren {
  ParentConnexionRoute: typeof ParentConnexionRoute
  ParentInscriptionRoute: typeof ParentInscriptionRoute
  ParentMotDePasseOublieRoute: typeof ParentMotDePasseOublieRoute
  ParentNouveauMotDePasseRoute: typeof ParentNouveauMotDePasseRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentConnexionRoute: ParentConnexionRoute,
  ParentInscriptionRoute: ParentInscriptionRoute,
  ParentMotDePasseOublieRoute: ParentMotDePasseOublieRoute,
  ParentNouveauMotDePasseRoute: ParentNouveauMotDePasseRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface FoyerRouteChildren {
  FoyerStudentIdRoute: typeof FoyerStudentIdRoute
  FoyerIndexRoute: typeof FoyerIndexRoute
}

const FoyerRouteChildren: FoyerRouteChildren = {
  FoyerStudentIdRoute: FoyerStudentIdRoute,
  FoyerIndexRoute: FoyerIndexRoute,
}

const FoyerRouteWithChildren = FoyerRoute._addFileChildren(FoyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentRoute: ParentRouteWithChildren,
  ErreurConnexionRoute: ErreurConnexionRoute,
  FoyerRoute: FoyerRouteWithChildren,
  JumelerRoute: JumelerRoute,
  MemoireRoute: MemoireRoute,
  SeanceSessionIdRoute: SeanceSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
