/**
 * BM25 tokeniser parity test — TS implementation must produce byte-identical
 * indices/values to the Python reference (`tomai-curriculum/schema/bm25.py`).
 *
 * The fixture is generated by
 * `tomai-curriculum/scripts/dump_bm25_fixture.py`:
 *
 *   uv run python scripts/dump_bm25_fixture.py > .../bm25_parity.json
 *
 * Every entry is `{ text, tokens, token_hashes: [[token, hash], ...] }`. We
 * re-run the TS tokeniser + FNV-1a hash on the same text and assert equality
 * pair-by-pair. Any divergence (regex tweak, case-fold rule, hash bit width)
 * breaks the contract — Python ingests with indice X, TS queries with indice
 * Y, Qdrant IDF goes incoherent, recall drops silently.
 */

import { describe, it, expect } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { hashTokenFnv1a, tokenizeFr, toSparseVector } from '@repo/shared-types';

interface FixtureEntry {
  text: string;
  tokens: string[];
  token_hashes: [string, number][];
}

const FIXTURE_PATH = join(import.meta.dir, 'fixtures', 'bm25_parity.json');
const fixtures = JSON.parse(readFileSync(FIXTURE_PATH, 'utf-8')) as FixtureEntry[];

describe('BM25 tokeniser parity (TS ↔ Python)', () => {
  it.each(fixtures.map((f, i) => [`fixture[${i}] "${f.text.slice(0, 30)}…"`, f]))(
    '%s — same tokens',
    (_label, fixture) => {
      const tokens = tokenizeFr(fixture.text);
      expect(tokens).toEqual(fixture.tokens);
    },
  );

  it.each(fixtures.map((f, i) => [`fixture[${i}] "${f.text.slice(0, 30)}…"`, f]))(
    '%s — same FNV-1a hashes',
    (_label, fixture) => {
      for (const [token, expectedHash] of fixture.token_hashes) {
        expect(hashTokenFnv1a(token)).toBe(expectedHash);
      }
    },
  );

  it('toSparseVector dedups + counts', () => {
    // Reproduces the Python invariant: repeated tokens collapse to a single
    // index whose value is the term frequency.
    const sv = toSparseVector('chat chat chien chien chien chat');
    expect(sv.indices.length).toBe(2);
    const chatIdx = hashTokenFnv1a('chat');
    const chienIdx = hashTokenFnv1a('chien');
    const pairs = new Map(sv.indices.map((idx, i) => [idx, sv.values[i] as number]));
    expect(pairs.get(chatIdx)).toBe(3);
    expect(pairs.get(chienIdx)).toBe(3);
  });

  it('handles empty input', () => {
    expect(tokenizeFr('')).toEqual([]);
    expect(toSparseVector('').indices).toEqual([]);
  });

  it('strips punctuation, keeps digits', () => {
    expect(tokenizeFr('123, abc-def.')).toEqual(['123', 'abc', 'def']);
  });

  it('lowercases input', () => {
    expect(tokenizeFr('Pythagore PYTHAGORE pythagore')).toEqual([
      'pythagore',
      'pythagore',
      'pythagore',
    ]);
  });
});
