/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/children` | `/children`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/children` | `/children`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/learning` | `/learning`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/children${`?${string}` | `#${string}` | ''}` | `/children${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(student)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/learning${`?${string}` | `#${string}` | ''}` | `/learning${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/children` | `/children`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
