#!/usr/bin/env bash
# Computes current baseline metrics and outputs markdown to stdout.
# Run: bash scripts/compute-baseline.sh > docs/metrics/baseline-<date>.md

set -euo pipefail

REPO="${REPO:-VictorNain26/tomai-monorepo}"
DATE=$(date -u +%Y-%m-%d)

echo "# Baseline metrics — $DATE"
echo ""
echo "Generated by scripts/compute-baseline.sh."
echo ""

# --- time-to-ship proxy: merge date of last 20 PRs to main ---
echo "## Time-to-ship (proxy: last 20 PRs merged to main)"
echo ""
echo "| PR | Merged at | Lag (since opened) |"
echo "|---|---|---|"
gh pr list --repo "$REPO" --state merged --base main --limit 20 --json number,mergedAt,createdAt,title \
  | jq -r '.[] | "| #\(.number) \(.title) | \(.mergedAt) | \((.mergedAt | fromdateiso8601) - (.createdAt | fromdateiso8601) | . / 3600 | floor)h |"' \
  || echo "| n/a | | |"
echo ""

# --- bug rate: closed bugs in last 8 weeks ---
echo "## Bug rate (closed issues labeled \`bug\`)"
echo ""
SINCE=$(date -u -d '8 weeks ago' +%Y-%m-%d 2>/dev/null || date -u -v-8w +%Y-%m-%d 2>/dev/null || echo "2026-02-28")
BUGS=$(gh issue list --repo "$REPO" --state closed --label bug --search "closed:>$SINCE" --json number --jq 'length' 2>/dev/null || echo "0")
echo "- Closed bugs since $SINCE: **$BUGS**"
echo "- Weekly rate: **$(awk "BEGIN { printf \"%.1f\", $BUGS / 8 }")**"
echo ""

# --- MTTR proxy: incidents closed ---
echo "## MTTR (issues labeled \`incident\`)"
echo ""
MTTR_DATA=$(gh issue list --repo "$REPO" --state closed --label incident --limit 10 --json number,createdAt,closedAt,title 2>/dev/null || echo "[]")
if [ "$MTTR_DATA" = "[]" ] || [ "$(echo "$MTTR_DATA" | jq length)" = "0" ]; then
  echo "- No \`incident\` labeled issues yet (baseline)"
else
  echo "| Issue | Created | Closed | MTTR (h) |"
  echo "|---|---|---|---|"
  echo "$MTTR_DATA" | jq -r '.[] | "| #\(.number) \(.title) | \(.createdAt) | \(.closedAt) | \((.closedAt | fromdateiso8601) - (.createdAt | fromdateiso8601) | . / 3600 | floor) |"'
fi
echo ""

# --- test coverage (best effort — don't fail the whole script if tests fail) ---
echo "## Test coverage"
echo ""
echo "### Server (bun)"
echo '```'
(cd apps/server && bun run test --coverage 2>&1 | tail -20) || echo "test run failed or no tests"
echo '```'
echo ""
echo "### Mobile (jest-expo)"
echo '```'
(cd apps/mobile && pnpm test --coverage 2>&1 | tail -30) || echo "test run failed or no tests"
echo '```'
echo ""

# --- agent PR merge rate (bootstrap = 0) ---
echo "## Agent PR merge rate"
echo ""
echo "- Baseline at phase 0 start: **0** (no agents merging to staging yet)"
echo "- Track: PRs opened by \`app/claude-code\`, \`github-actions[bot]\`, or label \`agent:safe\`"
echo ""

echo "---"
echo "Run again with: \`bash scripts/compute-baseline.sh > docs/metrics/snapshots/\$(date +%Y-%m).md\`"
